// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqiwvhzdnozxgabguogq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxaXd2aHpkbm96eGdhYmd1b2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNzYwMjEsImV4cCI6MjA2NDg1MjAyMX0.C2t5NOsCsXMdlHVOnVi3WYiiEEuF615E_x6927ZwYB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);